# Generated by Django 2.1.5 on 2019-02-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='name',
            field=models.CharField(default='', max_length=250),
        ),
    ]
