# Generated by Django 2.1.5 on 2019-02-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20190210_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='filename',
        ),
        migrations.AddField(
            model_name='photo',
            name='file',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
